### ISSUE TITLE
Clarify Span format 

### ISSUE THREAD

**Issue by githubsands** [xmidt-org/wrp-c#66]
Within the **CRUD message** definition & **Simple Request-Response Definition** clarify **_spans_** correct data format.  Currently it is in the air to what the final form should be: a strings to strings, or a map of strings to strings.

The WRP lists the current **_spans_** format as:
_"An array of arrays of timing values as a list in the format: "name", "start time", "duration""_

**Comment by schmidtw** [comment]
Updated:
https://github.com/Comcast/wrp-c/wiki/Web-Routing-Protocol/_compare/b470d8ea98c74d3aa4fba29b34a18209bfdf435f...05ca9510c3cb66d6701d39b5a0babfa4c9d01713

**Comment by schmidtw** [comment]
At this point we plan to deprecate support for spans in favor of adopting opentelemetry support for b3 and w3c instructions.  The resulting trace data will be a separate WRP.Event targeted to: `event:opentelemetry/tracing` or similar.
