### ISSUE TITLE
Update spec to include a new field for WRP Event types

### ISSUE THREAD

**Issue by joe94** [xmidt-org/wrp-c#81]
`session_id` should be added as a top-level property of all WRP messages that represent events.
The field represents a unique identifier that represents a single connection session between a device and talaria.

**Comment by schmidtw** [comment]
I'm planning on including this in the 2.0.0 release as `session_id` as specified [here](https://github.com/xmidt-org/docs/issues/80).

**Comment by schmidtw** [comment]
Resolved in the #111
