### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/wrp-c#82]
Also have to change references to the branch in .travis.yml, README, and CONTRIBUTING. Double check any other markdown files as well - sometimes links have the branch name in them.

**Comment by schmidtw** [comment]
Fixed by PR #84 .

**Comment by schmidtw** [comment]
This had to be temporarily undone.

**Comment by schmidtw** [comment]
We have moved over to use `main` going forward.
